apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j4w1y6ey5-nodejs 
  janus-idp.io/tekton: j4w1y6ey5-nodejs
  backstage.io/kubernetes-id: j4w1y6ey5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j4w1y6ey5-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  